using System;
using System.Linq;
using System.Text;
using DomainFixture.TestGenerator.Modules;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class CompileTimeModuleCatalogEmitter
{
    public const string HintName = "DomainFixture.ModuleCatalog.g.cs";

    public static void Emit(
        SourceProductionContext context,
        CompileTimeModuleCatalog catalog)
    {
        if (catalog.Modules.IsEmpty)
            return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// DomainFixture compile-time modules accepted for this test compilation:");
        foreach (var module in catalog.Modules)
        {
            source.Append("// MODULE ").Append(OneLine(module.ModuleId))
                .Append(" | version=").Append(OneLine(module.ModuleVersion))
                .Append(" | source=").Append(OneLine(module.SourceTypeName))
                .Append(" | capabilities=")
                .AppendLine(string.Join(",", module.Capabilities.Select(OneLine)));
        }
        foreach (var recipe in catalog.Recipes)
        {
            source.Append("// RECIPE ").Append(OneLine(recipe.SubjectTypeName))
                .Append(" | ").Append(OneLine(recipe.ConfigurationNamespace))
                .Append('.').Append(OneLine(recipe.ConfigurationName))
                .Append('.').Append(OneLine(recipe.RecipeName))
                .Append(" | module=").AppendLine(OneLine(recipe.ModuleId));
        }
        foreach (var validation in catalog.Validations)
        {
            source.Append("// VALIDATION ").Append(OneLine(validation.SubjectTypeName))
                .Append(" | adapter=").Append(OneLine(validation.AdapterTypeName))
                .Append(" | module=").AppendLine(OneLine(validation.ModuleId));
        }

        source.AppendLine("namespace DomainFixture.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal static class DomainFixtureModuleCatalog");
        source.AppendLine("    {");
        source.Append("        internal const int ModuleCount = ")
            .Append(catalog.Modules.Length).AppendLine(";");
        source.Append("        internal const int RecipeContributionCount = ")
            .Append(catalog.Recipes.Length).AppendLine(";");
        source.Append("        internal const int ValidationContributionCount = ")
            .Append(catalog.Validations.Length).AppendLine(";");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource(HintName, SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string OneLine(string value) =>
        (value ?? string.Empty)
        .Replace("\r", " ")
        .Replace("\n", " ");
}
