using System;
using System.Linq;
using System.Text;
using DomainFixture.Contracts;
using DomainFixture.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class DomainSpecSnapshotEmitter
{
    public const string HintName = "DomainFixture.DomainSpecSnapshot.g.cs";

    public static void Emit(
        SourceProductionContext context,
        DomainSpecNormalizationResult normalization,
        GenerationProfileSpec? profile = null) =>
        context.AddSource(HintName, SourceText.From(EmitSource(normalization, profile), Encoding.UTF8));

    internal static string EmitSource(
        DomainSpecNormalizationResult normalization,
        GenerationProfileSpec? profile = null)
    {
        if (normalization is null) throw new ArgumentNullException(nameof(normalization));

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// DomainFixture normalized domain specification");
        foreach (var value in (profile ?? GenerationProfileSpec.Default).ConfiguredValues
                     .OrderBy(value => value.TypeName, StringComparer.Ordinal))
        {
            source.Append("// CONFIGURED VALUE ").Append(OneLine(value.TypeName))
                .Append(" = ").AppendLine(OneLine(value.Expression));
        }
        foreach (var type in normalization.Types.OrderBy(type => type.SubjectTypeName, StringComparer.Ordinal))
        {
            source.Append("// TYPE ").AppendLine(OneLine(type.SubjectTypeName));
            foreach (var recipe in type.Recipes)
            {
                source.Append("//   RECIPE ").Append(OneLine(recipe.Name))
                    .Append(" | configuration=").Append(OneLine(recipe.Configuration.ConfigurationName))
                    .Append(" | baseline=").Append(OneLine(recipe.Configuration.BaselineFactoryExpression))
                    .Append(" | provenance=Configuration | source=").AppendLine(OneLine(recipe.SourceId));
            }

            foreach (var property in type.Properties.OrderBy(property => property.Name, StringComparer.Ordinal))
            {
                source.Append("//   PROPERTY ").Append(OneLine(property.Name))
                    .Append(" : ").Append(OneLine(property.TypeName))
                    .Append(" | readable=").Append(property.CanReadFromGeneratedCode ? "true" : "false")
                    .Append(" | assignable=").Append(property.CanBeAssigned ? "true" : "false")
                    .AppendLine(" | provenance=Configuration");
            }

            foreach (var fact in type.Constraints
                         .OrderBy(fact => fact.Value.MemberPath, StringComparer.Ordinal)
                         .ThenBy(fact => fact.Value.KindId, StringComparer.Ordinal)
                         .ThenBy(fact => fact.SourceId, StringComparer.Ordinal))
            {
                source.Append("//   CONSTRAINT ").Append(OneLine(fact.Value.MemberPath))
                    .Append(" | kind=").Append(OneLine(fact.Value.KindId))
                    .Append(" | parameters=").Append(FormatParameters(fact.Value))
                    .Append(" | failure=").Append(OneLine(fact.Value.FailureCode ?? "<none>"));
                AppendFactOrigin(source, fact);
            }

            foreach (var fact in type.Operations
                         .OrderBy(fact => fact.Value.OperationId, StringComparer.Ordinal))
            {
                source.Append("//   OPERATION ").Append(OneLine(fact.Value.OperationId))
                    .Append(" | kind=").Append(OneLine(fact.Value.KindId))
                    .Append(" | member=").Append(OneLine(fact.Value.DeclaringTypeName))
                    .Append('.').Append(OneLine(fact.Value.MemberName))
                    .Append(" | returns=").Append(OneLine(fact.Value.ReturnTypeName))
                    .Append(" | parameters=").Append(FormatOperationParameters(fact.Value));
                AppendFactOrigin(source, fact);
            }

            foreach (var fact in type.Outcomes
                         .OrderBy(fact => fact.Value.OperationId, StringComparer.Ordinal)
                         .ThenBy(fact => fact.Value.KindId, StringComparer.Ordinal))
            {
                source.Append("//   OUTCOME ").Append(OneLine(fact.Value.OperationId))
                    .Append(" | kind=").Append(OneLine(fact.Value.KindId))
                    .Append(" | parameters=")
                    .Append(OneLine(string.Join(",", fact.Value.Parameters)));
                AppendFactOrigin(source, fact);
            }

            foreach (var fact in type.Scenarios
                         .OrderBy(fact => fact.Value.KindId, StringComparer.Ordinal)
                         .ThenBy(fact => FormatParameters(fact.Value), StringComparer.Ordinal))
            {
                source.Append("//   SCENARIO ").Append(OneLine(fact.Value.KindId))
                    .Append(" | parameters=").Append(FormatParameters(fact.Value));
                AppendFactOrigin(source, fact);
            }
        }

        foreach (var conflict in normalization.OperationConflicts
                     .OrderBy(conflict => conflict.SubjectTypeName, StringComparer.Ordinal)
                     .ThenBy(conflict => conflict.OperationId, StringComparer.Ordinal))
        {
            source.Append("// CONFLICT operation ").Append(OneLine(conflict.OperationId))
                .Append(" | subject=").Append(OneLine(conflict.SubjectTypeName))
                .Append(" | sources=").Append(OneLine(conflict.Existing.SourceId))
                .Append(',').AppendLine(OneLine(conflict.Candidate.SourceId));
        }

        foreach (var failure in normalization.ManifestFailures
                     .OrderBy(failure => failure.OperationId, StringComparer.Ordinal)
                     .ThenBy(failure => failure.Kind))
        {
            source.Append("// MANIFEST FAILURE ").Append(OneLine(failure.OperationId))
                .Append(" | kind=").Append(failure.Kind)
                .Append(" | reason=").AppendLine(OneLine(failure.Message));
        }

        source.AppendLine("#nullable enable");
        source.AppendLine("namespace DomainFixture.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal static class DomainSpecSnapshot");
        source.AppendLine("    {");
        source.Append("        internal const int TypeCount = ").Append(normalization.Types.Length).AppendLine(";");
        source.Append("        internal const int RecipeCount = ")
            .Append(normalization.Types.Sum(type => type.Recipes.Length)).AppendLine(";");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendFactOrigin<T>(StringBuilder source, DomainFact<T> fact) =>
        source.Append(" | provenance=").Append(fact.Provenance)
            .Append(" | source=").AppendLine(OneLine(fact.SourceId));

    private static string FormatParameters(DomainConstraintContract contract) =>
        OneLine(string.Join(",", contract.Parameters
            .OrderBy(parameter => parameter.Key, StringComparer.Ordinal)
            .Select(parameter => $"{parameter.Key}={parameter.Value}")));

    private static string FormatParameters(DomainScenarioContract contract) =>
        OneLine(string.Join(",", contract.Parameters
            .OrderBy(parameter => parameter.Key, StringComparer.Ordinal)
            .Select(parameter => $"{parameter.Key}={parameter.Value}")));

    private static string FormatOperationParameters(DomainOperationContract contract) =>
        OneLine(string.Join(",", contract.Parameters.Select(parameter =>
            $"{parameter.Name}:{parameter.TypeName}->{parameter.MemberPath}")));

    private static string OneLine(string value) =>
        value.Replace("\r", " ").Replace("\n", " ");
}
