using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DomainFixture.Contracts;
using DomainFixture.SourceGenerator.Generation;
using DomainFixture.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class DomainCoverageReportEmitter
{
    public const string HintName = "DomainFixture.DomainCoverageReport.g.cs";

    public static void Emit(
        SourceProductionContext context,
        DomainSpecNormalizationResult normalization,
        GenerationProfileSpec? profile = null) =>
        context.AddSource(HintName, SourceText.From(EmitSource(normalization, profile), Encoding.UTF8));

    internal static string EmitSource(
        DomainSpecNormalizationResult normalization,
        GenerationProfileSpec? profile = null)
    {
        var report = Analyze(normalization, profile);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// DomainFixture domain coverage report");
        foreach (var group in report.Facts.GroupBy(fact => fact.SubjectTypeName))
        {
            source.Append("// TYPE ").AppendLine(OneLine(group.Key));
            foreach (var fact in group)
            {
                source.Append("//   [").Append(fact.Classification).Append("] ")
                    .Append(OneLine(fact.Category)).Append(' ')
                    .Append(OneLine(fact.FactId)).Append(" | ")
                    .AppendLine(OneLine(fact.Reason));
            }
        }

        source.Append("// TOTAL facts=").Append(report.Total)
            .Append(" factory=").Append(report.Factory)
            .Append(" test=").Append(report.Test)
            .Append(" both=").Append(report.Both)
            .Append(" uncovered=").AppendLine(report.Uncovered.ToString());
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace DomainFixture.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal static class DomainCoverageReport");
        source.AppendLine("    {");
        source.Append("        internal const int Total = ").Append(report.Total).AppendLine(";");
        source.Append("        internal const int Factory = ").Append(report.Factory).AppendLine(";");
        source.Append("        internal const int Test = ").Append(report.Test).AppendLine(";");
        source.Append("        internal const int Both = ").Append(report.Both).AppendLine(";");
        source.Append("        internal const int Uncovered = ").Append(report.Uncovered).AppendLine(";");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    internal static DomainCoverageReport Analyze(
        DomainSpecNormalizationResult normalization,
        GenerationProfileSpec? profile = null)
    {
        if (normalization is null) throw new ArgumentNullException(nameof(normalization));

        var facts = new List<DomainCoverageFact>();
        foreach (var type in normalization.Types.OrderBy(type => type.SubjectTypeName, StringComparer.Ordinal))
        {
            var hasRecipe = type.Recipes.Length > 0;
            var factoryPlanning = ResolveFactoryPlan(
                normalization,
                type,
                profile ?? GenerationProfileSpec.Default,
                new HashSet<string>(StringComparer.Ordinal));
            var factoryPlan = factoryPlanning.Plan;
            var factoryFailure = factoryPlanning.UncoveredReasons.Length == 0
                ? "no valid-instance provider covered this type"
                : string.Join("; ", factoryPlanning.UncoveredReasons);
            var hasTestFacts = type.Constraints.Length > 0 ||
                               type.ConstructionOperations.Length > 0 ||
                               type.Outcomes.Length > 0 ||
                               type.Scenarios.Length > 0;
            foreach (var recipe in type.Recipes)
            {
                facts.Add(new DomainCoverageFact(
                    type.SubjectTypeName,
                    "Recipe",
                    recipe.SourceId,
                    hasTestFacts
                        ? DomainCoverageClassification.Both
                        : DomainCoverageClassification.Factory,
                    hasTestFacts
                        ? "the recipe baseline emits a factory and anchors normalized generated tests"
                        : "the recipe baseline emits a factory; no normalized test facts target this type"));
            }

            foreach (var property in type.Properties.OrderBy(property => property.Name, StringComparer.Ordinal))
            {
                var factoryCoversProperty = factoryPlan is not null &&
                    (factoryPlan.ChosenOperation is null || factoryPlan.Parameters.Any(parameter =>
                        parameter.Parameter.MemberPath == property.Name));
                var referencedByTest = type.Constraints.Any(constraint =>
                                           constraint.Value.MemberPath == property.Name) ||
                                       type.ConstructionOperations.Any(operation =>
                                           operation.Value.Parameters.Any(parameter =>
                                               parameter.MemberPath == property.Name));
                facts.Add(new DomainCoverageFact(
                    type.SubjectTypeName,
                    "Property",
                    property.Name,
                    Classify(factoryCoversProperty, hasRecipe && referencedByTest),
                    Describe(
                        factoryCoversProperty,
                        hasRecipe && referencedByTest,
                        factoryPlan?.ChosenOperation is null
                            ? "a recipe baseline creates this property"
                            : "the synthesized factory operation binds this property",
                        "a constraint or operation exercises this property",
                        hasRecipe
                            ? "no normalized factory or test fact covers this property"
                            : factoryFailure)));
            }

            foreach (var constraint in type.Constraints
                         .OrderBy(fact => fact.Value.MemberPath, StringComparer.Ordinal)
                         .ThenBy(fact => fact.Value.KindId, StringComparer.Ordinal)
                         .ThenBy(fact => fact.SourceId, StringComparer.Ordinal))
            {
                var factoryCovered = factoryPlan?.ChosenOperation is not null &&
                    factoryPlan.Parameters.Any(parameter =>
                        parameter.Parameter.MemberPath == constraint.Value.MemberPath &&
                        parameter.Provenance is ValidInstanceProvenance.StringConstraint or
                            ValidInstanceProvenance.Int32Constraint);
                var testCovered = hasRecipe;
                facts.Add(new DomainCoverageFact(
                    type.SubjectTypeName,
                    "Constraint",
                    $"{constraint.Value.MemberPath}:{constraint.Value.KindId}",
                    Classify(factoryCovered, testCovered),
                    Describe(
                        factoryCovered,
                        testCovered,
                        "the synthesized factory derives a valid argument from this constrained member",
                        "a recipe anchors boundary-test generation for this constraint",
                        hasRecipe ? "this constraint is not consumed by a supported generator" : factoryFailure)));
            }

            foreach (var operation in type.Operations
                         .OrderBy(fact => fact.Value.OperationId, StringComparer.Ordinal))
            {
                var factoryCovered = factoryPlan?.ChosenOperation?.OperationId ==
                                     operation.Value.OperationId;
                var testCovered = hasRecipe;
                var behaviorOperation = operation.Value.KindId == DomainOperationKinds.InstanceCommand;
                facts.Add(new DomainCoverageFact(
                    type.SubjectTypeName,
                    "Operation",
                    operation.Value.OperationId,
                    Classify(factoryCovered, testCovered),
                    Describe(
                        factoryCovered,
                        testCovered,
                        "the synthesized factory invokes this construction operation",
                        behaviorOperation
                            ? "a recipe anchors generated behavioral assertions for this command"
                            : "a recipe anchors construction success and round-trip tests for this operation",
                        factoryFailure)));
            }

            foreach (var outcome in type.Outcomes
                         .OrderBy(fact => fact.Value.OperationId, StringComparer.Ordinal)
                         .ThenBy(fact => fact.Value.KindId, StringComparer.Ordinal))
            {
                var operation = type.ConstructionOperations.FirstOrDefault(candidate =>
                    candidate.Value.OperationId == outcome.Value.OperationId);
                var mapsConstraint = operation is not null && type.Constraints.Any(constraint =>
                    operation.Value.Parameters.Any(parameter =>
                        parameter.MemberPath == constraint.Value.MemberPath));
                var covered = hasRecipe && operation is not null && mapsConstraint;
                var reason = !hasRecipe
                    ? "no recipe anchors rejection-test generation for this type"
                    : operation is null
                        ? "the outcome has no matching normalized construction operation"
                        : !mapsConstraint
                            ? "the operation has no parameter mapped to a normalized constrained member"
                            : "a matching constrained operation produces rejection tests for this outcome";
                facts.Add(new DomainCoverageFact(
                    type.SubjectTypeName,
                    "Outcome",
                    $"{outcome.Value.OperationId}:{outcome.Value.KindId}",
                    covered ? DomainCoverageClassification.Test : DomainCoverageClassification.Uncovered,
                    reason));
            }

            foreach (var scenario in type.Scenarios
                         .OrderBy(fact => fact.Value.KindId, StringComparer.Ordinal)
                         .ThenBy(fact => ScenarioKey(fact.Value), StringComparer.Ordinal))
            {
                facts.Add(TestFact(
                    type,
                    "Scenario",
                    ScenarioKey(scenario.Value),
                    hasRecipe,
                    "a recipe anchors generated scenario assertions"));
            }
        }

        return new DomainCoverageReport(facts);
    }

    private static ValidInstancePlanningResult ResolveFactoryPlan(
        DomainSpecNormalizationResult normalization,
        DomainTypeSpec type,
        GenerationProfileSpec profile,
        HashSet<string> activeTypes)
    {
        if (!activeTypes.Add(type.SubjectTypeName))
            return ValidInstancePlanningResult.Uncovered(
                $"nested construction cycle detected at '{type.SubjectTypeName}'");

        return ValidInstanceProviderPipeline.Resolve(
            new ValidInstancePlanningRequest(
                type,
                type.Recipes.FirstOrDefault(),
                nestedTypeName =>
                {
                    var nestedType = normalization.Types.FirstOrDefault(candidate =>
                        candidate.SubjectTypeName == nestedTypeName);
                    if (nestedType is null)
                        return NestedValidInstanceResolution.Uncovered(
                            $"no normalized domain type exists for '{nestedTypeName}'");
                    var nested = ResolveFactoryPlan(
                        normalization,
                        nestedType,
                        profile,
                        new HashSet<string>(activeTypes, StringComparer.Ordinal));
                    return nested.IsCovered
                        ? NestedValidInstanceResolution.Covered(nested.Plan!.Expression)
                        : NestedValidInstanceResolution.Uncovered(
                            string.Join("; ", nested.UncoveredReasons));
                },
                profile.ConfiguredValues));
    }

    private static DomainCoverageFact TestFact(
        DomainTypeSpec type,
        string category,
        string factId,
        bool covered,
        string coveredReason) =>
        new(
            type.SubjectTypeName,
            category,
            factId,
            covered ? DomainCoverageClassification.Test : DomainCoverageClassification.Uncovered,
            covered
                ? coveredReason
                : "no recipe anchors generated tests for this type");

    private static DomainCoverageClassification Classify(bool factory, bool test) =>
        factory && test
            ? DomainCoverageClassification.Both
            : factory
                ? DomainCoverageClassification.Factory
                : test
                    ? DomainCoverageClassification.Test
                    : DomainCoverageClassification.Uncovered;

    private static string Describe(
        bool factory,
        bool test,
        string factoryReason,
        string testReason,
        string uncoveredReason) =>
        factory && test
            ? $"{factoryReason}; {testReason}"
            : factory
                ? factoryReason
                : test
                    ? testReason
                    : uncoveredReason;

    private static string ScenarioKey(DomainScenarioContract scenario)
    {
        var parameters = string.Join(",", scenario.Parameters
            .OrderBy(parameter => parameter.Key, StringComparer.Ordinal)
            .Select(parameter => $"{parameter.Key}={parameter.Value}"));
        return parameters.Length == 0 ? scenario.KindId : $"{scenario.KindId}:{parameters}";
    }

    private static string OneLine(string value) =>
        value.Replace("\r", " ").Replace("\n", " ");
}
