using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DomainFixture.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class FixtureFactorySourceEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ConfigurationParseResult configurationResult,
        Func<FixtureGenerationSpec, bool>? canExposePublicFactory = null)
    {
        if (configurationResult.Diagnostics.Any(diagnostic =>
                diagnostic.Severity == DiagnosticSeverity.Error))
        {
            return;
        }

        foreach (var group in configurationResult.Configurations.GroupBy(configuration => new
                 {
                     configuration.NamespaceName,
                     configuration.ConfigurationName,
                 }))
        {
            var configurations = group.ToArray();
            if (HasRecipeIdentifierCollision(configurations))
                continue;

            var source = EmitSource(configurations, canExposePublicFactory);
            source = GeneratedSourceAliasRewriter.Rewrite(
                source,
                configurations.SelectMany(configuration =>
                    GeneratedTypeReferenceCollector.Collect(configuration)),
                group.Key.NamespaceName);
            var hintName = CreateHintName(group.Key.NamespaceName, group.Key.ConfigurationName);
            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    internal static string EmitSource(
        IReadOnlyCollection<FixtureGenerationSpec> configurations,
        Func<FixtureGenerationSpec, bool>? canExposePublicFactory = null)
    {
        if (configurations.Count == 0)
            throw new ArgumentException("At least one fixture recipe is required.", nameof(configurations));

        var first = configurations.First();
        if (configurations.Any(configuration =>
                configuration.ConfigurationName != first.ConfigurationName ||
                configuration.NamespaceName != first.NamespaceName))
        {
            throw new ArgumentException(
                "All fixture recipes must belong to the same configuration and namespace.",
                nameof(configurations));
        }

        if (HasRecipeIdentifierCollision(configurations))
        {
            throw new ArgumentException(
                "Fixture recipe names must map to unique C# identifiers.",
                nameof(configurations));
        }

        var accessibility = canExposePublicFactory is not null &&
                            configurations.All(canExposePublicFactory)
            ? "public"
            : "internal";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("namespace ").Append(first.NamespaceName).AppendLine();
        source.AppendLine("{");
        source.Append("    ").Append(accessibility).Append(" static class ")
            .Append(first.ConfigurationName).AppendLine("Factory");
        source.AppendLine("    {");

        foreach (var configuration in configurations)
        {
            EmitRecipe(source, configuration, accessibility);
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    internal static string CreateRecipeIdentifier(string recipeName)
    {
        if (string.IsNullOrEmpty(recipeName))
            return "_";

        var identifier = new StringBuilder(recipeName.Length + 1);
        for (var index = 0; index < recipeName.Length; index++)
        {
            var character = recipeName[index];
            if (index == 0 && SyntaxFacts.IsIdentifierPartCharacter(character) &&
                !SyntaxFacts.IsIdentifierStartCharacter(character))
            {
                identifier.Append('_').Append(character);
                continue;
            }

            var valid = index == 0
                ? SyntaxFacts.IsIdentifierStartCharacter(character)
                : SyntaxFacts.IsIdentifierPartCharacter(character);
            identifier.Append(valid ? character : '_');
        }

        if (!SyntaxFacts.IsIdentifierStartCharacter(identifier[0]))
            identifier.Insert(0, '_');

        var result = identifier.ToString();
        return SyntaxFacts.GetKeywordKind(result) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(result) != SyntaxKind.None
            ? "@" + result
            : result;
    }

    internal static bool HasRecipeIdentifierCollision(
        IEnumerable<FixtureGenerationSpec> configurations)
    {
        return configurations
            .GroupBy(configuration => CreateRecipeIdentifier(configuration.RecipeName),
                StringComparer.Ordinal)
            .Any(group => group.Count() > 1);
    }

    private static void EmitRecipe(
        StringBuilder source,
        FixtureGenerationSpec configuration,
        string accessibility)
    {
        var recipeIdentifier = CreateRecipeIdentifier(configuration.RecipeName);
        source.Append("        ").Append(accessibility).Append(" static class ")
            .Append(recipeIdentifier).AppendLine();
        source.AppendLine("        {");
        source.Append("            ").Append(accessibility).Append(" static ")
            .Append(configuration.SubjectTypeName).AppendLine(" Create()");
        source.AppendLine("            {");
        source.Append("                return ").Append(configuration.BaselineFactoryExpression)
            .AppendLine(";");
        source.AppendLine("            }");
        source.AppendLine();
        source.Append("            ").Append(accessibility).Append(" static ")
            .Append(configuration.SubjectTypeName).Append(" Create(global::System.Func<")
            .Append(configuration.SubjectTypeName).Append(", ")
            .Append(configuration.SubjectTypeName).AppendLine("> transform)");
        source.AppendLine("            {");
        source.AppendLine("                if (transform is null)");
        source.AppendLine("                    throw new global::System.ArgumentNullException(nameof(transform));");
        source.AppendLine();
        source.AppendLine("                return transform(Create());");
        source.AppendLine("            }");
        source.AppendLine("        }");
    }

    private static string CreateHintName(string namespaceName, string configurationName)
    {
        var hintName = $"{namespaceName}.{configurationName}.Factory.g.cs";
        var invalidCharacters = System.IO.Path.GetInvalidFileNameChars();
        return new string(hintName
            .Select(character => invalidCharacters.Contains(character) ? '_' : character)
            .ToArray());
    }
}
