using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class UniqueValueSourceEmitter
{
    internal const string StringFactoryExpression =
        "global::DomainFixture.Generated.DomainFixtureUniqueValue.NextString";
    internal const string TypeName =
        "global::DomainFixture.Generated.DomainFixtureUniqueValue";

    public static void Emit(SourceProductionContext context) =>
        context.AddSource(
            "DomainFixture.UniqueValues.g.cs",
            SourceText.From(EmitSource(), Encoding.UTF8));

    internal static string EmitSource() =>
        @"// <auto-generated />
#nullable enable
namespace DomainFixture.Generated
{
    internal static class DomainFixtureUniqueValue
    {
        private const string Alphabet = ""0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"";
        private static long _sequence;
        private static int _emptyIssued;

        internal static string NextString(int minimumLength, int maximumLength)
        {
            if (minimumLength < 0)
                throw new global::System.ArgumentOutOfRangeException(nameof(minimumLength));
            if (maximumLength < minimumLength)
                throw new global::System.ArgumentOutOfRangeException(nameof(maximumLength));
            if (maximumLength == 0)
            {
                if (global::System.Threading.Interlocked.Exchange(ref _emptyIssued, 1) != 0)
                    throw new global::System.InvalidOperationException(""The only zero-length string value was already issued."");
                return string.Empty;
            }

            var sequence = global::System.Threading.Interlocked.Increment(ref _sequence);
            if (sequence <= 0)
                throw new global::System.InvalidOperationException(""The generated unique-value sequence was exhausted."");

            var value = Encode((ulong)sequence);
            if (value.Length > maximumLength)
            {
                throw new global::System.InvalidOperationException(
                    $""The unique string space for maximum length {maximumLength} was exhausted."");
            }

            return value.PadLeft(minimumLength, '0');
        }

        private static string Encode(ulong value)
        {
            var buffer = new char[11];
            var index = buffer.Length;
            do
            {
                buffer[--index] = Alphabet[(int)(value % (ulong)Alphabet.Length)];
                value /= (ulong)Alphabet.Length;
            }
            while (value > 0);

            return new string(buffer, index, buffer.Length - index);
        }
    }
}
";
}
