using System.Collections.Immutable;
using System.Linq;
using System.Text;
using DomainFixture.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class ValidationRuleManifestEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<RuleExtractionResult> results)
    {
        var rules = results
            .Where(result => result.Rule is not null)
            .Select(result => result.Rule!)
            .ToArray();
        if (rules.Length == 0)
            return;

        var source = new StringBuilder("// <auto-generated />\n");
        foreach (var rule in rules)
        {
            source.Append("[assembly: global::DomainFixture.Generation.Metadata.ValidationRuleManifestAttribute(typeof(")
                .Append(rule.ValidationRulesTypeKey)
                .Append("), typeof(")
                .Append(rule.SubjectTypeKey)
                .Append("), ")
                .Append(Quote(rule.PropertyName))
                .Append(", global::DomainFixture.Generation.Metadata.ValidationRuleManifestKind.")
                .Append(rule.Kind)
                .Append(", ")
                .Append(rule.Minimum ?? -1)
                .Append(", ")
                .Append(rule.Maximum ?? -1)
                .Append(", ")
                .Append(rule.ErrorCode is null ? "null" : Quote(rule.ErrorCode))
                .Append(", ")
                .Append(rule.PropertyCanBeAssigned ? "true" : "false")
                .Append(")]\n");
        }

        context.AddSource(
            "DomainFixture.ValidationRuleManifest.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Quote(string value) =>
        SyntaxFactory.LiteralExpression(
            SyntaxKind.StringLiteralExpression,
            SyntaxFactory.Literal(value)).ToFullString();
}
