using System.Collections.Immutable;
using System.Linq;
using System.Text;
using DomainFixture.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.SourceGenerator.Emission;

internal static class ValidationRuleManifestEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ConstraintExtractionResult> results)
    {
        var rules = results
            .Where(result => result.Constraint is not null)
            .Select(result => result.Constraint!)
            .ToArray();
        if (rules.Length == 0)
            return;

        var source = new StringBuilder("// <auto-generated />\n");
        foreach (var rule in rules)
        {
            source.Append("[assembly: global::DomainFixture.Generation.Metadata.DomainContractManifestAttribute(")
                .Append(rule.Contract.SchemaVersion)
                .Append(", typeof(")
                .Append(rule.SourceTypeKey)
                .Append("), typeof(")
                .Append(rule.SubjectTypeKey)
                .Append("), ")
                .Append(Quote(rule.PropertyName))
                .Append(", ")
                .Append(Quote(rule.KindId))
                .Append(", ")
                .Append("new string[] { ")
                .Append(string.Join(", ", rule.Contract.Parameters
                    .OrderBy(parameter => parameter.Key)
                    .Select(parameter => Quote($"{parameter.Key}={parameter.Value}"))))
                .Append(" }")
                .Append(", ")
                .Append(rule.ErrorCode is null ? "null" : Quote(rule.ErrorCode))
                .Append(", ")
                .Append(rule.PropertyCanBeAssigned ? "true" : "false")
                .Append(")]\n");
        }

        context.AddSource(
            "DomainFixture.ValidationRuleManifest.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Quote(string value) =>
        SyntaxFactory.LiteralExpression(
            SyntaxKind.StringLiteralExpression,
            SyntaxFactory.Literal(value)).ToFullString();
}
