using System;
using Registration = global::DomainFixture.Tests.Domain.Entities.Registration;

// <auto-generated />
#nullable enable
namespace DomainFixture.Tests.Generation
{
    public static class RegistrationFixtureFactory
    {
        public static class Pending
        {
            public static Registration Create()
            {
                return RegistrationFixture.Pending();
            }

            public static Registration Create(Func<Registration, Registration> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }

        public static class Approved
        {
            public static Registration Create()
            {
                return RegistrationFixture.Approved();
            }

            public static Registration Create(Func<Registration, Registration> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }
    }
}
