using System;
using ResultDisplayName = global::DomainFixture.Tests.Domain.ValueObjects.ResultDisplayName;

// <auto-generated />
#nullable enable
namespace DomainFixture.Tests.Generation
{
    public static class ResultDisplayNameFixtureFactory
    {
        public static class Valid
        {
            public static ResultDisplayName Create()
            {
                return new Func<ResultDisplayName>(() =>
                {
                    var result = ResultDisplayName.Create("a");
                    if (!result.IsSuccess)
                        throw new InvalidOperationException("The configured result factory did not produce a successful value.");
                    return result.Value;
                })();
            }

            public static ResultDisplayName Create(Func<ResultDisplayName, ResultDisplayName> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }
    }
}
