using System;
using DomainFixtureUniqueValue = global::DomainFixture.Generated.DomainFixtureUniqueValue;
using Subscription = global::DomainFixture.Tests.Domain.Entities.Subscription;

// <auto-generated />
#nullable enable
namespace DomainFixture.Tests.Generation
{
    public static class SubscriptionFixtureFactory
    {
        public static class Valid
        {
            public static Subscription Create()
            {
                return Subscription.Create(DomainFixtureUniqueValue.NextString(1, 2147483647), 1, Guid.NewGuid());
            }

            public static Subscription Create(Func<Subscription, Subscription> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }
    }
}
