using System;
using System.Collections.Generic;
using BillingCycle = global::DomainFixture.Tests.Domain.Entities.BillingCycle;
using TenantSubscription = global::DomainFixture.Tests.Domain.Entities.TenantSubscription;
using Username = global::DomainFixture.Tests.Domain.ValueObjects.Username;

// <auto-generated />
#nullable enable
namespace DomainFixture.Tests.Generation
{
    public static class TenantSubscriptionFixtureFactory
    {
        public static class Valid
        {
            public static TenantSubscription Create()
            {
                return TenantSubscription.Create(UsernameFixtureFactory.Validation.Create(), new Username[]{UsernameFixtureFactory.Validation.Create()}, new Dictionary<string, Username>{["a"] = UsernameFixtureFactory.Validation.Create()}, BillingCycle.Monthly);
            }

            public static TenantSubscription Create(Func<TenantSubscription, TenantSubscription> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }
    }
}
