using System;
using Username = global::DomainFixture.Tests.Domain.ValueObjects.Username;

// <auto-generated />
#nullable enable
namespace DomainFixture.Tests.Generation
{
    public static class UsernameFixtureFactory
    {
        public static class Validation
        {
            public static Username Create()
            {
                return UsernameFixture.Baseline();
            }

            public static Username Create(Func<Username, Username> transform)
            {
                if (transform is null)
                    throw new ArgumentNullException(nameof(transform));
                return transform(Create());
            }
        }
    }
}
