<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <LangVersion>10</LangVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\DomainFixture\DomainFixture.csproj" />
    <ProjectReference Include="..\..\..\src\DomainFixture.SourceGenerator\DomainFixture.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\src\DomainFixture.TestGenerator\DomainFixture.TestGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\src\DomainFixture.Contracts\DomainFixture.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\DomainFixture.Contracts\DomainFixture.Contracts.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\OrderingShipping.SharedKernel\OrderingShipping.SharedKernel.csproj" />
    <ProjectReference Include="..\OrderingShipping.Orders\OrderingShipping.Orders.csproj" />
    <ProjectReference Include="..\OrderingShipping.Shipping\OrderingShipping.Shipping.csproj" />
  </ItemGroup>

  <Target Name="CleanMaterializedCompilerGeneratedFiles" BeforeTargets="CoreCompile">
    <RemoveDir Directories="$(CompilerGeneratedFilesOutputPath)" />
  </Target>

</Project>
