using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DomainFixture.Modules.FluentValidation;

internal static class FluentValidationModuleEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ValidatorCandidate> candidates)
    {
        foreach (var diagnostic in candidates.SelectMany(candidate => candidate.Diagnostics))
            context.ReportDiagnostic(diagnostic);
        if (candidates.IsEmpty)
            return;

        var valid = RemoveInvalidAndDuplicateValidators(candidates);
        valid = RemoveAmbiguousSubjects(context, valid);
        if (valid.Length == 0)
            return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        AppendModuleManifest(source);
        foreach (var candidate in valid)
        {
            AppendValidationManifest(source, candidate);
            foreach (var rule in candidate.Rules)
                AppendRuleManifest(source, rule);
        }

        source.Append("namespace ")
            .Append(FluentValidationModuleConstants.GeneratedNamespace)
            .AppendLine();
        source.AppendLine("{");
        source.AppendLine("    internal sealed class FluentValidationModuleMarker { }");
        foreach (var candidate in valid)
            AppendAdapter(source, candidate);
        source.AppendLine("}");

        context.AddSource(
            FluentValidationModuleConstants.HintName,
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static ValidatorCandidate[] RemoveInvalidAndDuplicateValidators(
        ImmutableArray<ValidatorCandidate> candidates) =>
        candidates
            .Where(candidate => !candidate.Diagnostics.Any(diagnostic =>
                diagnostic.Severity == DiagnosticSeverity.Error))
            .GroupBy(candidate => candidate.ValidatorTypeName, StringComparer.Ordinal)
            .Select(group => group.First())
            .ToArray();

    private static ValidatorCandidate[] RemoveAmbiguousSubjects(
        SourceProductionContext context,
        ValidatorCandidate[] candidates)
    {
        var ambiguousSubjects = candidates
            .GroupBy(candidate => candidate.SubjectTypeName, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .ToArray();
        foreach (var ambiguous in ambiguousSubjects)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                FluentValidationDiagnostics.AmbiguousValidator,
                ambiguous.Skip(1).First().Location,
                ambiguous.Key,
                string.Join(", ", ambiguous.Select(candidate => candidate.ValidatorTypeName))));
        }

        var ambiguousNames = new HashSet<string>(
            ambiguousSubjects.Select(group => group.Key),
            StringComparer.Ordinal);
        return candidates
            .Where(candidate => !ambiguousNames.Contains(candidate.SubjectTypeName))
            .ToArray();
    }

    private static void AppendModuleManifest(StringBuilder source)
    {
        source.AppendLine("[assembly: global::DomainFixture.Generation.Metadata.DomainFixtureModuleManifestAttribute(");
        source.AppendLine("    1,");
        source.Append("    ").Append(Literal(FluentValidationModuleConstants.ModuleId)).AppendLine(",");
        source.Append("    ").Append(Literal(FluentValidationModuleConstants.ModuleVersion)).AppendLine(",");
        source.Append("    typeof(global::")
            .Append(FluentValidationModuleConstants.MarkerTypeName).AppendLine("),");
        source.AppendLine("    new string[]");
        source.AppendLine("    {");
        source.AppendLine("        \"domainfixture.module.constraints\",");
        source.AppendLine("        \"domainfixture.module.validators\"");
        source.AppendLine("    })]");
        source.AppendLine();
    }

    private static void AppendValidationManifest(
        StringBuilder source,
        ValidatorCandidate candidate)
    {
        source.AppendLine("[assembly: global::DomainFixture.Generation.Metadata.DomainFixtureValidationManifestAttribute(");
        source.AppendLine("    1,");
        source.Append("    ").Append(Literal(FluentValidationModuleConstants.ModuleId)).AppendLine(",");
        source.Append("    typeof(global::")
            .Append(FluentValidationModuleConstants.MarkerTypeName).AppendLine("),");
        source.Append("    typeof(").Append(candidate.SubjectTypeName).AppendLine("),");
        source.Append("    ").Append(Literal("global::" + candidate.AdapterTypeName)).AppendLine(")]");
        source.AppendLine();
    }

    private static void AppendRuleManifest(StringBuilder source, RuleContribution rule)
    {
        source.AppendLine("[assembly: global::DomainFixture.Generation.Metadata.DomainContractManifestAttribute(");
        source.AppendLine("    1,");
        source.Append("    typeof(global::")
            .Append(FluentValidationModuleConstants.MarkerTypeName).AppendLine("),");
        source.Append("    typeof(").Append(rule.SubjectTypeName).AppendLine("),");
        source.Append("    ").Append(Literal(rule.PropertyName)).AppendLine(",");
        source.Append("    ").Append(Literal(rule.KindId)).AppendLine(",");
        source.Append("    new string[] { ");
        var parameters = new List<string>();
        if (rule.Minimum is not null)
            parameters.Add("minimum=" + rule.Minimum.Value.ToString(CultureInfo.InvariantCulture));
        if (rule.Maximum is not null)
            parameters.Add("maximum=" + rule.Maximum.Value.ToString(CultureInfo.InvariantCulture));
        source.Append(string.Join(", ", parameters.Select(Literal))).AppendLine(" },");
        source.Append("    ")
            .Append(rule.ErrorCode is null ? "null" : Literal(rule.ErrorCode)).AppendLine(",");
        source.Append("    ")
            .Append(rule.PropertyCanBeAssigned ? "true" : "false").AppendLine(")]");
        source.AppendLine();
    }

    private static void AppendAdapter(StringBuilder source, ValidatorCandidate candidate)
    {
        source.Append("    public sealed class ").Append(candidate.AdapterClassName)
            .Append(" : global::DomainFixture.Validation.IFixtureValidator<")
            .Append(candidate.SubjectTypeName).AppendLine(">");
        source.AppendLine("    {");
        source.Append("        private readonly ").Append(candidate.ValidatorTypeName)
            .Append(" _validator = new ").Append(candidate.ValidatorTypeName).AppendLine("();");
        source.Append("        public global::DomainFixture.Validation.ValidationReport Validate(")
            .Append(candidate.SubjectTypeName).AppendLine(" subject)");
        source.AppendLine("        {");
        source.Append("            var context = new global::FluentValidation.ValidationContext<")
            .Append(candidate.SubjectTypeName).AppendLine(">(subject);");
        source.AppendLine("            var result = _validator.Validate(context);");
        source.AppendLine("            var failures = new global::System.Collections.Generic.List<global::DomainFixture.Validation.ValidationFailure>();");
        source.AppendLine("            foreach (var error in result.Errors)");
        source.AppendLine("            {");
        source.AppendLine("                failures.Add(new global::DomainFixture.Validation.ValidationFailure(error.PropertyName, error.ErrorCode, error.ErrorMessage));");
        source.AppendLine("            }");
        source.AppendLine("            return new global::DomainFixture.Validation.ValidationReport(failures);");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static string Literal(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);
}
